// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-suppliers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_suppliers_default = defineTool({
  name: "list_suppliers",
  title: "List suppliers",
  description: "List active suppliers in the signed-in user's organization. Returns id, name, email, phone, and contact_person.",
  inputSchema: {
    limit: z.number().int().optional().describe("Max number of suppliers to return. Defaults to 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const capped = Math.min(Math.max(limit ?? 50, 1), 200);
    const { data, error } = await supabaseForUser(ctx).from("suppliers").select("id, name, email, phone, contact_person, is_active").eq("is_active", true).order("name", { ascending: true }).limit(capped);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { suppliers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_orders_default = defineTool2({
  name: "list_orders",
  title: "List recent orders",
  description: "List recent orders for the signed-in user's organization, newest first. Optionally filter by status.",
  inputSchema: {
    limit: z2.number().int().optional().describe("Max orders to return. Defaults to 20."),
    status: z2.string().optional().describe("Optional status filter (e.g. pending, confirmed, delivered, cancelled).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const capped = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser2(ctx).from("orders").select("id, order_number, supplier_id, status, total_amount, notes, created_at").order("created_at", { ascending: false }).limit(capped);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-articles.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_articles_default = defineTool3({
  name: "search_articles",
  title: "Search articles",
  description: "Search articles in the signed-in user's organization by name (case-insensitive). Optionally filter by supplier_id.",
  inputSchema: {
    query: z3.string().describe("Substring to match against the article name."),
    supplier_id: z3.string().optional().describe("Optional supplier UUID filter."),
    limit: z3.number().int().optional().describe("Max results. Defaults to 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, supplier_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const capped = Math.min(Math.max(limit ?? 25, 1), 100);
    let q = supabaseForUser3(ctx).from("articles").select("id, name, sku, unit, price, packaging_unit, category, top_category, supplier_id, is_active").eq("is_active", true).ilike("name", `%${query}%`).order("name", { ascending: true }).limit(capped);
    if (supplier_id) q = q.eq("supplier_id", supplier_id);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-order.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_order_default = defineTool4({
  name: "get_order",
  title: "Get order details",
  description: "Fetch a single order (with its line items) by order id or order_number, scoped to the signed-in user's organization.",
  inputSchema: {
    order_id: z4.string().optional().describe("Order UUID."),
    order_number: z4.string().optional().describe("Human-readable order number (e.g. ORD-2026-01-0001).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_id, order_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!order_id && !order_number) {
      return {
        content: [{ type: "text", text: "Provide order_id or order_number." }],
        isError: true
      };
    }
    const sb = supabaseForUser4(ctx);
    let query = sb.from("orders").select(
      "id, order_number, supplier_id, status, total_amount, notes, created_at, updated_at, order_items(id, article_id, article_name, quantity, unit_price, total_price, unit)"
    ).limit(1);
    if (order_id) query = query.eq("id", order_id);
    else if (order_number) query = query.eq("order_number", order_number);
    const { data, error } = await query.maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Order not found." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/tools/create-order.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_order_default = defineTool5({
  name: "create_order",
  title: "Create order",
  description: "Create a new order for a supplier with one or more line items. Prices, units and totals are looked up from the article records \u2014 never trusted from the caller. Runs as the signed-in user; RLS enforces that the supplier and articles belong to the user's organization. If no delivery_address is provided, the organization's default location address is used.",
  inputSchema: {
    supplier_id: z5.string().uuid().describe("Supplier UUID the order is placed with."),
    items: z5.array(
      z5.object({
        article_id: z5.string().uuid().describe("Article UUID."),
        quantity: z5.number().int().positive().describe("Quantity of packaging units to order.")
      })
    ).min(1).describe("Line items. At least one required."),
    location_id: z5.string().uuid().optional().describe("Optional location UUID this order is booked against."),
    delivery_address: z5.string().optional().describe("Delivery address. Defaults to the organization's default location address."),
    notes: z5.string().optional().describe("Optional free-text note attached to the order."),
    is_test_order: z5.boolean().optional().describe("Mark as test order (safely deletable by admins/managers). Defaults to false.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ supplier_id, items, location_id, delivery_address, notes, is_test_order }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser5(ctx);
    const userId = ctx.getUserId();
    const { data: profile, error: profileError } = await supabase.from("profiles").select("organization_id").eq("id", userId).single();
    if (profileError) {
      return { content: [{ type: "text", text: profileError.message }], isError: true };
    }
    const organizationId = profile?.organization_id;
    if (!organizationId) {
      return { content: [{ type: "text", text: "No organization for user" }], isError: true };
    }
    let resolvedAddress = delivery_address?.trim();
    if (!resolvedAddress) {
      const defaultLocationQuery = supabase.from("locations").select("id, address, name, is_default").eq("organization_id", organizationId);
      const { data: locations, error: locError } = location_id ? await defaultLocationQuery.eq("id", location_id).limit(1) : await defaultLocationQuery.eq("is_default", true).limit(1);
      if (locError) {
        return { content: [{ type: "text", text: locError.message }], isError: true };
      }
      const loc = locations?.[0];
      resolvedAddress = (loc?.address ?? loc?.name ?? "").trim();
    }
    if (!resolvedAddress) {
      return {
        content: [
          {
            type: "text",
            text: "delivery_address is required (no default location address available)."
          }
        ],
        isError: true
      };
    }
    const articleIds = Array.from(new Set(items.map((i) => i.article_id)));
    const { data: articles, error: articlesError } = await supabase.from("articles").select("id, name, price, unit, packaging_unit, order_unit_id, supplier_id, is_active").in("id", articleIds);
    if (articlesError) {
      return { content: [{ type: "text", text: articlesError.message }], isError: true };
    }
    const articleMap = /* @__PURE__ */ new Map();
    for (const a of articles ?? []) articleMap.set(a.id, a);
    for (const id of articleIds) {
      const a = articleMap.get(id);
      if (!a) {
        return {
          content: [{ type: "text", text: `Article ${id} not found or not accessible.` }],
          isError: true
        };
      }
      if (a.supplier_id !== supplier_id) {
        return {
          content: [
            {
              type: "text",
              text: `Article ${id} does not belong to supplier ${supplier_id}.`
            }
          ],
          isError: true
        };
      }
      if (a.is_active === false) {
        return {
          content: [{ type: "text", text: `Article ${id} is inactive.` }],
          isError: true
        };
      }
    }
    const orderUnitIds = Array.from(
      new Set(
        (articles ?? []).map((a) => a.order_unit_id).filter((v) => Boolean(v))
      )
    );
    const orderUnitNameById = /* @__PURE__ */ new Map();
    if (orderUnitIds.length > 0) {
      const { data: units } = await supabase.from("order_units").select("id, name").in("id", orderUnitIds);
      for (const u of units ?? []) {
        orderUnitNameById.set(u.id, u.name);
      }
    }
    const { data: orderNumber, error: orderNumberError } = await supabase.rpc(
      "generate_order_number"
    );
    if (orderNumberError) {
      return { content: [{ type: "text", text: orderNumberError.message }], isError: true };
    }
    const lineTotals = items.map(({ article_id, quantity }) => {
      const a = articleMap.get(article_id);
      const price = Number(a.price);
      const pack = Number(a.packaging_unit ?? 1) || 1;
      return {
        article: a,
        quantity,
        unit_price: price,
        total_price: price * pack * quantity
      };
    });
    const totalAmount = lineTotals.reduce((sum, l) => sum + l.total_price, 0);
    const { data: order, error: orderError } = await supabase.from("orders").insert({
      order_number: orderNumber,
      organization_id: organizationId,
      supplier_id,
      user_id: userId,
      location_id: location_id ?? null,
      total_amount: totalAmount,
      delivery_address: resolvedAddress,
      notes: notes ?? null,
      is_test_order: is_test_order ?? false
    }).select("id, order_number, status, total_amount, created_at").single();
    if (orderError) {
      return { content: [{ type: "text", text: orderError.message }], isError: true };
    }
    const orderItemsPayload = lineTotals.map(({ article, quantity, unit_price, total_price }) => ({
      order_id: order.id,
      article_id: article.id,
      article_name: article.name,
      quantity,
      unit: article.unit,
      order_unit: article.order_unit_id ? orderUnitNameById.get(article.order_unit_id) ?? null : null,
      unit_price,
      total_price,
      is_free_text_item: false
    }));
    const { error: itemsError } = await supabase.from("order_items").insert(orderItemsPayload);
    if (itemsError) {
      await supabase.from("orders").delete().eq("id", order.id);
      return { content: [{ type: "text", text: itemsError.message }], isError: true };
    }
    const result = {
      id: order.id,
      order_number: order.order_number,
      status: order.status,
      total_amount: order.total_amount,
      created_at: order.created_at,
      item_count: orderItemsPayload.length
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: { order: result }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lclhwmxpbpmqtiwmgmgm";
var mcp_default = defineMcp({
  name: "bestellung-pro-mcp",
  title: "Bestellung.pro MCP",
  version: "0.1.0",
  instructions: "Tools for a Bestellung.pro account: list suppliers, search articles, list recent orders, fetch a single order with its line items, and create new orders. All calls run as the signed-in user; data is scoped to that user's organization via row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_suppliers_default,
    list_orders_default,
    search_articles_default,
    get_order_default,
    create_order_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
