// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-suppliers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_suppliers_default = defineTool({
  name: "list_suppliers",
  title: "List suppliers",
  description: "List active suppliers in the signed-in user's organization. Returns id, name, email, phone, and contact_person.",
  inputSchema: {
    limit: z.number().int().optional().describe("Max number of suppliers to return. Defaults to 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const capped = Math.min(Math.max(limit ?? 50, 1), 200);
    const { data, error } = await supabaseForUser(ctx).from("suppliers").select("id, name, email, phone, contact_person, is_active").eq("is_active", true).order("name", { ascending: true }).limit(capped);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { suppliers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_orders_default = defineTool2({
  name: "list_orders",
  title: "List recent orders",
  description: "List recent orders for the signed-in user's organization, newest first. Optionally filter by status.",
  inputSchema: {
    limit: z2.number().int().optional().describe("Max orders to return. Defaults to 20."),
    status: z2.string().optional().describe("Optional status filter (e.g. pending, confirmed, delivered, cancelled).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const capped = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser2(ctx).from("orders").select("id, order_number, supplier_id, status, total_amount, notes, created_at").order("created_at", { ascending: false }).limit(capped);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-articles.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_articles_default = defineTool3({
  name: "search_articles",
  title: "Search articles",
  description: "Search articles in the signed-in user's organization by name (case-insensitive). Optionally filter by supplier_id.",
  inputSchema: {
    query: z3.string().describe("Substring to match against the article name."),
    supplier_id: z3.string().optional().describe("Optional supplier UUID filter."),
    limit: z3.number().int().optional().describe("Max results. Defaults to 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, supplier_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const capped = Math.min(Math.max(limit ?? 25, 1), 100);
    let q = supabaseForUser3(ctx).from("articles").select("id, name, sku, unit, price, packaging_unit, category, top_category, supplier_id, is_active").eq("is_active", true).ilike("name", `%${query}%`).order("name", { ascending: true }).limit(capped);
    if (supplier_id) q = q.eq("supplier_id", supplier_id);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-order.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_order_default = defineTool4({
  name: "get_order",
  title: "Get order details",
  description: "Fetch a single order (with its line items) by order id or order_number, scoped to the signed-in user's organization.",
  inputSchema: {
    order_id: z4.string().optional().describe("Order UUID."),
    order_number: z4.string().optional().describe("Human-readable order number (e.g. ORD-2026-01-0001).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_id, order_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!order_id && !order_number) {
      return {
        content: [{ type: "text", text: "Provide order_id or order_number." }],
        isError: true
      };
    }
    const sb = supabaseForUser4(ctx);
    let query = sb.from("orders").select(
      "id, order_number, supplier_id, status, total_amount, notes, created_at, updated_at, order_items(id, article_id, article_name, quantity, unit_price, total_price, unit)"
    ).limit(1);
    if (order_id) query = query.eq("id", order_id);
    else if (order_number) query = query.eq("order_number", order_number);
    const { data, error } = await query.maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Order not found." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lclhwmxpbpmqtiwmgmgm";
var mcp_default = defineMcp({
  name: "bestellung-pro-mcp",
  title: "Bestellung.pro MCP",
  version: "0.1.0",
  instructions: "Tools to inspect a Bestellung.pro account: list suppliers, search articles, list recent orders, and fetch a single order with its line items. All calls run as the signed-in user; data is scoped to that user's organization via row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_suppliers_default, list_orders_default, search_articles_default, get_order_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
